// ---------------------------------------------------------------------------
// Mock fixtures used as a fallback while the Express backend is being built.
// Whenever `NEXT_PUBLIC_API_BASE_URL` is not configured (or the backend call
// fails in development), `lib/api.ts` resolves promises with this data so the
// UI stays fully interactive. Every shape mirrors `lib/types.ts` exactly.
// ---------------------------------------------------------------------------

import type {
  AdminDashboard,
  AdminLeaderboard,
  Catalog,
  InnovationWall,
  Mission,
  Problem,
  StudentDashboard,
  StudentLeaderboard,
  Submission,
  User,
} from "./types";

export const mockCatalog: Catalog = {
  departments: ["CCS", "COE", "CBA", "CAS", "COED"],
  tiers: [
    { value: "bronze", label: "🪙 Bronze", points: 10 },
    { value: "silver", label: "⭐ Silver", points: 50 },
    { value: "gold", label: "🌟 Gold", points: 150 },
    { value: "contest", label: "🔥 Contest", points: 500 },
  ],
  sdgs: [
    "SDG 1 — No Poverty",
    "SDG 3 — Good Health",
    "SDG 4 — Quality Education",
    "SDG 6 — Clean Water",
    "SDG 11 — Sustainable Cities",
    "SDG 13 — Climate Action",
    "SDG 15 — Life on Land",
  ],
  categories: ["Sustainability", "Education", "Wellness", "Innovation", "Community"],
  durations: ["1 day", "1 week", "2 weeks", "1 month", "1 semester"],
};

export const mockMissions: Mission[] = [
  {
    id: "m-1",
    title: "BRING YOUR OWN TUMBLER",
    description: "Refill at the campus water station for 5 days straight. Photo proof daily.",
    tier: "bronze",
    status: "live",
    department: "CAS",
    sdg: "SDG 13",
    category: "Sustainability",
    points: 10,
    duration: "5 days",
    rewards: "Digital badge + 10 coins per refill",
    participants: 127,
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "m-2",
    title: "PEER TUTOR SESSION",
    description: "Run a 1-hour tutoring session for juniors in your dept. Submit attendance sheet.",
    tier: "silver",
    status: "live",
    department: "COED",
    sdg: "SDG 4",
    category: "Education",
    points: 50,
    duration: "1 week",
    rewards: "150 coins + Tutor badge + library priority slot",
    participants: 58,
    createdAt: "2026-03-02T00:00:00.000Z",
    updatedAt: "2026-03-02T00:00:00.000Z",
  },
  {
    id: "m-3",
    title: "CAMPUS CLEAN-UP DRIVE",
    description: "Organize a 20-person clean-up squad. Document before/after photos plus signed list.",
    tier: "gold",
    status: "draft",
    department: "CBA",
    sdg: "SDG 11",
    category: "Community",
    points: 150,
    duration: "2 weeks",
    rewards: "10 coins per session + Eco starter pack",
    participants: 0,
    createdAt: "2026-03-03T00:00:00.000Z",
    updatedAt: "2026-03-03T00:00:00.000Z",
  },
  {
    id: "m-4",
    title: "HACKATHON: GREEN DEVS",
    description: "48-hour build for sustainable code. Requires event code.",
    tier: "contest",
    status: "live",
    department: "CCS",
    sdg: "SDG 9",
    category: "Innovation",
    points: 500,
    duration: "48 hrs",
    rewards: "₱10k cash pool · Top 3 internships · 500 coins each",
    eventCode: "HACK2026",
    participants: 32,
    createdAt: "2026-03-04T00:00:00.000Z",
    updatedAt: "2026-03-04T00:00:00.000Z",
  },
  {
    id: "m-5",
    title: "REPORT A LEAK",
    description: "Spot a leaky tap on campus? Snap and report it via the app.",
    tier: "bronze",
    status: "ended",
    department: "COE",
    sdg: "SDG 6",
    category: "Sustainability",
    points: 10,
    duration: "Anytime",
    rewards: "10 coins per valid report",
    participants: 41,
    createdAt: "2026-02-20T00:00:00.000Z",
    updatedAt: "2026-03-10T00:00:00.000Z",
  },
  {
    id: "m-6",
    title: "PLANT A TREE",
    description: "Plant and tag a sapling in the assigned zone. Monthly check-in for 3 months.",
    tier: "silver",
    status: "live",
    department: "CAS",
    sdg: "SDG 15",
    category: "Sustainability",
    points: 50,
    duration: "3 months",
    rewards: "20 coins per check-in + Tree planter badge",
    participants: 84,
    createdAt: "2026-03-05T00:00:00.000Z",
    updatedAt: "2026-03-05T00:00:00.000Z",
  },
  {
    id: "m-7",
    title: "MENTAL HEALTH WORKSHOP",
    description: "Host a 2-hr session with the guidance office. Submit feedback forms.",
    tier: "gold",
    status: "live",
    department: "COED",
    sdg: "SDG 3",
    category: "Wellness",
    points: 150,
    duration: "3 weeks",
    rewards: "150 coins + Wellness badge",
    participants: 12,
    createdAt: "2026-03-07T00:00:00.000Z",
    updatedAt: "2026-03-07T00:00:00.000Z",
  },
  {
    id: "m-8",
    title: "RESEARCH PITCH NIGHT",
    description: "Present an SDG-aligned research idea to the panel. Event code required.",
    tier: "contest",
    status: "live",
    department: "CCS",
    sdg: "SDG 4",
    category: "Innovation",
    points: 500,
    duration: "1 night",
    rewards: "Conference scholarship + 500 coins",
    eventCode: "PITCH2026",
    participants: 18,
    createdAt: "2026-03-09T00:00:00.000Z",
    updatedAt: "2026-03-09T00:00:00.000Z",
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: "s-1",
    missionId: "m-1",
    missionTitle: "BRING YOUR OWN TUMBLER · DAY 3",
    missionTier: "bronze",
    playerId: "u-mario",
    playerName: "Mario Rossi",
    playerDepartment: "CCS",
    playerYear: "2nd year",
    summary: "Refilled at the library station, no plastic for 3 days now!",
    status: "pending",
    submittedAt: "2026-04-22T08:00:00.000Z",
  },
  {
    id: "s-2",
    missionId: "m-3",
    missionTitle: "CAMPUS CLEAN-UP DRIVE",
    missionTier: "gold",
    playerId: "u-luigi",
    playerName: "Luigi Verdi",
    playerDepartment: "COE",
    playerYear: "3rd year",
    summary: "22 volunteers, 14 bags of waste collected at quad and parking lot.",
    status: "pending",
    submittedAt: "2026-04-22T05:00:00.000Z",
  },
  {
    id: "s-3",
    missionId: "m-4",
    missionTitle: "HACKATHON — GREEN DEVS",
    missionTier: "contest",
    playerId: "u-peach",
    playerName: "Princess Peach",
    playerDepartment: "CCS",
    playerYear: "4th year",
    summary: "Built an energy-monitor dashboard for dorms. Repo attached.",
    eventCode: "HACK2026",
    status: "pending",
    submittedAt: "2026-04-21T10:00:00.000Z",
  },
  {
    id: "s-4",
    missionId: "m-2",
    missionTitle: "PEER TUTOR SESSION",
    missionTier: "silver",
    playerId: "u-toad",
    playerName: "Toad Kinopio",
    playerDepartment: "CAS",
    playerYear: "2nd year",
    summary: "1.5-hour algebra session for 8 freshmen. Attendance attached.",
    status: "pending",
    submittedAt: "2026-04-21T09:00:00.000Z",
  },
];

export const mockProblems: Problem[] = [
  {
    id: "p-1",
    title: "🥡 CAFETERIA USES SINGLE-USE PLASTIC UTENSILS DAILY",
    description:
      "Every meal comes with a plastic spoon, fork, straw and we serve about 1,200 meals a day.",
    location: "Cafeteria",
    postedByRole: "faculty",
    postedByName: "Dr. Bowser",
    upvotes: 47,
    createdAt: "2026-04-20T00:00:00.000Z",
    quests: [
      { tier: "bronze", text: "BYOC (Bring Your Own Cutlery) — Pledge and log 5 meals.", points: 10 },
      { tier: "silver", text: "Survey vendors — Identify 3 bamboo or biodegradable suppliers.", points: 50 },
      { tier: "gold", text: "Pilot proposal — Run a 1-week zero-plastic trial in one stall.", points: 150 },
    ],
  },
  {
    id: "p-2",
    title: "💡 LIBRARY LIGHTS STAY ON ALL NIGHT EVEN WHEN EMPTY",
    description: "After 10pm the library is empty but every floor stays fully lit until 6am.",
    location: "Main Library",
    postedByRole: "student",
    postedByName: "Yoshi",
    upvotes: 28,
    createdAt: "2026-04-18T00:00:00.000Z",
    quests: [
      { tier: "bronze", text: "Audit night usage — Photo log of empty floors after 10pm for 3 nights.", points: 10 },
      { tier: "silver", text: "Engineering brief — Cost-estimate motion-sensor retrofit.", points: 50 },
      { tier: "gold", text: "Proposal to admin — Present energy and savings calculation to Facilities.", points: 150 },
    ],
  },
  {
    id: "p-3",
    title: "🚲 NO SAFE BIKE PARKING NEAR ENGINEERING BUILDING",
    description: "Bikes are getting stolen weekly. Students just lock them on railings.",
    location: "COE entrance",
    postedByRole: "student",
    postedByName: "Toad",
    upvotes: 19,
    createdAt: "2026-04-15T00:00:00.000Z",
    quests: [
      { tier: "bronze", text: "Survey commuters — Get 50 signatures from bike users.", points: 10 },
      { tier: "silver", text: "Site mapping — Sketch 3 candidate locations with COE faculty.", points: 50 },
      { tier: "gold", text: "Build mock — Prototype a covered rack with the design club.", points: 150 },
    ],
  },
];

export const mockCurrentUser: User = {
  id: "u-mario",
  name: "Mario Rossi",
  role: "student",
  department: "CCS",
  year: "3rd year",
  totalCoins: 1420,
  currentRank: 42,
  questStreak: 7,
  badges: [
    { id: "b-1", label: "First Quest", icon: "🥇", unlocked: true },
    { id: "b-2", label: "10 Quests", icon: "⭐", unlocked: true },
    { id: "b-3", label: "Eco Warrior", icon: "🌱", unlocked: true },
    { id: "b-4", label: "Tutor", icon: "📚", unlocked: true },
    { id: "b-5", label: "Streak x7", icon: "🔥", unlocked: true },
    { id: "b-6", label: "Locked", icon: "?", unlocked: false },
    { id: "b-7", label: "Locked", icon: "?", unlocked: false },
    { id: "b-8", label: "Locked", icon: "?", unlocked: false },
  ],
};

export const mockStudentDashboard: StudentDashboard = {
  user: mockCurrentUser,
  history: [
    { id: "h-1", label: "✅ Bring Your Own Tumbler · Day 5", points: 10, status: "approved" },
    { id: "h-2", label: "✅ Peer Tutor Session", points: 50, status: "approved" },
    { id: "h-3", label: "✅ Report a Leak (3rd floor)", points: 10, status: "approved" },
    { id: "h-4", label: "⏳ Campus Clean-Up Drive", points: null, status: "pending" },
    { id: "h-5", label: "✅ Plant a Tree · Month 1 check-in", points: 20, status: "approved" },
  ],
  activeMissions: [
    {
      id: "m-6",
      tier: "silver",
      sdg: "SDG 15",
      title: "PLANT A TREE",
      description: "Month 2 check-in due in 6 days.",
      points: 20,
      timeLeft: "6d left",
    },
    {
      id: "m-4",
      tier: "contest",
      sdg: "SDG 9",
      title: "HACKATHON: GREEN DEVS",
      description: "48-hour build in progress.",
      points: 500,
      timeLeft: "12h left",
    },
  ],
};

export const mockAdminDashboard: AdminDashboard = {
  stats: { liveMissions: 42, pendingVerify: 18, activeStudents: 1284 },
  recentSubmissions: [
    { id: "rs-1", label: "Mario · Plant a Tree (Month 2)", status: "pending" },
    { id: "rs-2", label: "Luigi · Peer Tutor Session", status: "pending" },
    { id: "rs-3", label: "Peach · Bring Your Own Tumbler", status: "approved" },
    { id: "rs-4", label: "Toad · Campus Clean-Up Drive", status: "pending" },
    { id: "rs-5", label: "Yoshi · Hackathon: Green Devs", status: "approved" },
  ],
  liveMissions: [
    { id: "m-1", tier: "silver", title: "BRING YOUR OWN TUMBLER", meta: "127 players · ends in 4d" },
    { id: "m-2", tier: "gold", title: "PEER TUTOR SESSION", meta: "58 players · open" },
    { id: "m-4", tier: "contest", title: "HACKATHON: GREEN DEVS", meta: "32 teams · ends in 12h" },
  ],
};

export const mockStudentLeaderboard: StudentLeaderboard = {
  season: "SEASON 3 · SPRING 2026",
  daysRemaining: 47,
  individuals: [
    { rank: 1, playerId: "u-peach", playerName: "👑 Princess Peach", department: "CCS", quests: 34, coins: 4820 },
    { rank: 2, playerId: "u-luigi", playerName: "Luigi Verdi", department: "COE", quests: 29, coins: 4210 },
    { rank: 3, playerId: "u-toad", playerName: "Toad Kinopio", department: "CAS", quests: 26, coins: 3950 },
    { rank: 4, playerId: "u-yoshi", playerName: "Yoshi Green", department: "COED", quests: 22, coins: 3400 },
    { rank: 5, playerId: "u-daisy", playerName: "Daisy Sarasaland", department: "CBA", quests: 21, coins: 3150 },
  ],
  departments: [
    { rank: 1, name: "CCS — Computer Studies", players: 312, totalCoins: 48920 },
    { rank: 2, name: "COE — Engineering", players: 278, totalCoins: 42150 },
    { rank: 3, name: "CAS — Arts & Sciences", players: 241, totalCoins: 36400 },
    { rank: 4, name: "CBA — Business", players: 198, totalCoins: 29800 },
    { rank: 5, name: "COED — Education", players: 156, totalCoins: 22150 },
  ],
  currentUserPercentile: 96,
  nearbyPlayers: [
    { rank: 42, playerId: "u-mario", playerName: "🍄 Mario Rossi (YOU)", department: "CCS", quests: 14, coins: 1420, isCurrentUser: true },
    { rank: 43, playerId: "u-wario", playerName: "Wario Greedy", department: "CBA", quests: 13, coins: 1380 },
    { rank: 44, playerId: "u-bowser", playerName: "Bowser Koopa", department: "COE", quests: 13, coins: 1360 },
  ],
};

export const mockAdminLeaderboard: AdminLeaderboard = {
  moderationSnapshot: { proofsVerified: 318, proofsRejected: 27, missionsPublished: 14 },
  topModerators: [
    { rank: 1, name: "Admin Peach", missionsPosted: 42, proofsVerified: 318 },
    { rank: 2, name: "Admin Luigi", missionsPosted: 39, proofsVerified: 274 },
    { rank: 3, name: "Admin Daisy", missionsPosted: 35, proofsVerified: 251 },
    { rank: 4, name: "Admin Toad", missionsPosted: 33, proofsVerified: 230 },
    { rank: 5, name: "Admin Yoshi", missionsPosted: 29, proofsVerified: 198 },
  ],
  departments: mockStudentLeaderboard.departments,
};

export const mockInnovationWall: InnovationWall = {
  ticker: [
    { id: "t-1", text: "🪙 PEACH cleared HACKATHON (+500)" },
    { id: "t-2", text: "🌱 LUIGI cleared PLANT A TREE (+50)" },
    { id: "t-3", text: "📚 TOAD cleared PEER TUTOR (+50)" },
    { id: "t-4", text: "🪣 YOSHI cleared CLEAN-UP DRIVE (+150)" },
    { id: "t-5", text: "💧 DAISY cleared REPORT A LEAK (+10)" },
    { id: "t-6", text: "🔥 MARIO joined HACKATHON" },
  ],
  heatmap: [
    { number: 1, label: "NO POVERTY", completionCount: 12, intensity: 0.45 },
    { number: 2, label: "ZERO HUNGER", completionCount: 28, intensity: 0.55 },
    { number: 3, label: "HEALTH", completionCount: 142, intensity: 0.85 },
    { number: 4, label: "EDUCATION", completionCount: 318, intensity: 1 },
    { number: 5, label: "EQUALITY", completionCount: 66, intensity: 0.65 },
    { number: 6, label: "WATER", completionCount: 98, intensity: 0.75 },
    { number: 7, label: "ENERGY", completionCount: 34, intensity: 0.55 },
    { number: 8, label: "WORK", completionCount: 22, intensity: 0.5 },
    { number: 9, label: "INDUSTRY", completionCount: 210, intensity: 0.95 },
    { number: 10, label: "INEQUAL", completionCount: 14, intensity: 0.45 },
    { number: 11, label: "CITIES", completionCount: 186, intensity: 0.9 },
    { number: 12, label: "CONSUMP", completionCount: 82, intensity: 0.7 },
    { number: 13, label: "CLIMATE", completionCount: 274, intensity: 1 },
    { number: 14, label: "OCEANS", completionCount: 8, intensity: 0.4 },
    { number: 15, label: "LAND", completionCount: 158, intensity: 0.85 },
    { number: 16, label: "PEACE", completionCount: 30, intensity: 0.55 },
    { number: 17, label: "PARTNER", completionCount: 42, intensity: 0.6 },
  ],
  hottestQuests: [
    { id: "hq-1", label: "🥇 BRING YOUR OWN TUMBLER", players: 214 },
    { id: "hq-2", label: "🥈 HACKATHON — GREEN DEVS", players: 98 },
    { id: "hq-3", label: "🥉 PEER TUTOR SESSION", players: 76 },
    { id: "hq-4", label: "4. CAMPUS CLEAN-UP DRIVE", players: 52 },
    { id: "hq-5", label: "5. PLANT A TREE", players: 41 },
  ],
};
